let user = "Nino";
var userName = "giorgi";
const minAge =  25;
let surName = "miqeltadze";
let x = 5;
let y = 10;
console.log (user + " " + surName);
console.log (`${user} ${surName}`);
let sum = x+y;
console.log (sum);
let multiply = x *y;
console.log (multiply);
let division = x/y;
console.log (division);
 x = 7;
  y = 5;
let areaOfReactangle = x*y;
console.log (areaOfReactangle);
const radius = 7;
let areaOfCircle = 2 * Math.pi * radius;
console.log (areaOfCircle);
